/* gromit: FADNregionTO .java
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.farm;

import java.io.Serializable;
import java.lang.Long;
import java.lang.String;
import org.seamless_ip.ontologies.farm.FADNregion;
import org.seamless_ip.services.transferobjects.farm.IRegionTO;
import org.seamless_ip.services.transferobjects.utils.AbstractTO;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.farm.FADNregion", readonly=false, used=true)
@SuppressWarnings("serial")
public class FADNregionTO extends AbstractTO implements IRegionTO<FADNregionTO, FADNregion>, Serializable, Cloneable 	
{
	private String _shapefileid;		
	private String _name;		
	private String _label_gms;		
	private Long _id;		



	public FADNregionTO()
	{
		super();
	}

	public static FADNregion createDBInstance()
	{
		FADNregion dbItem = new FADNregion();
		return dbItem;
	}


	public static FADNregion createDBInstance(FADNregionTO toItem)
	{
		if (toItem != null)
			return toItem.assignTo(createDBInstance());
		else
			return createDBInstance();
	}
	
    public static void releaseDBInstance(FADNregion dbItem)
    {
        if (dbItem != null) {
        }
    }

    public FADNregionTO assignFrom(FADNregion target)	
	{
		if (target != null)
		{
			try {
					_id = target.getId();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_label_gms = target.getLabel_gms();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_name = target.getName();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_shapefileid = target.getShapeFileID();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
		}
		return this;
	}
    
    public FADNregion assignTo(FADNregion target)
    {
        if (target != null) 
        {
			target.setId(_id);			
			target.setLabel_gms(_label_gms);			
			target.setName(_name);			
			target.setShapeFileID(_shapefileid);			
        }
        return target;
    }	
    
    public boolean equalsTo(FADNregion target)
    {
        if (target == null)
            return false;

        FADNregionTO targetTO = new FADNregionTO().assignFrom(target);
        return targetTO.equals(this);
    }
    
    @Override
    public FADNregionTO clone()
    {
    	FADNregionTO clone = new FADNregionTO();
		clone.setId(_id);
		clone.setLabel_gms(_label_gms);
		clone.setName(_name);
		clone.setShapeFileID(_shapefileid);
        return clone;
    }    
    
    @Override
    public int hashCode()
    {
        int result = 0;
		result = 31 * result + (_shapefileid != null ? _shapefileid .hashCode() : 0);
		result = 31 * result + (_name != null ? _name .hashCode() : 0);
		result = 31 * result + (_label_gms != null ? _label_gms .hashCode() : 0);
		result = 31 * result + (_id != null ? _id .hashCode() : 0);
        return result;
    }    
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof FADNregionTO)) return false;

        FADNregionTO classTO = (FADNregionTO) o;

		if (_shapefileid != null ? !_shapefileid .equals(classTO._shapefileid) : classTO._shapefileid != null)
			return false;
		if (_name != null ? !_name .equals(classTO._name) : classTO._name != null)
			return false;
		if (_label_gms != null ? !_label_gms .equals(classTO._label_gms) : classTO._label_gms != null)
			return false;
		if (_id != null ? !_id .equals(classTO._id) : classTO._id != null)
			return false;
        
        return true;
    }
    
    public Long getId()
    {
		return _id;
    }
    public String getLabel()
    {
		return _name;
    }
    public String getLabel_gms()
    {
		return _label_gms;
    }
    public String getName()
    {
		return _name;
    }
    public String getShapeFileID()
    {
		return _shapefileid;
    }
    public void setId(Long value)
    {
		_id = value;
    }
    public void setLabel_gms(String value)
    {
		_label_gms = value;
    }
    public void setName(String value)
    {
		_name = value;
    }
    public void setShapeFileID(String value)
    {
		_shapefileid = value;
    }
}