/* gromit: IRegionListTO .java 
 * ==============================================================================
 * (This code was generated by a tool)
 * List of Transport Object class for IRegionTO .java
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */

package org.seamless_ip.services.transferobjects.farm;

import org.seamless_ip.ontologies.farm.IRegion;
import org.seamless_ip.services.transferobjects.farm.IRegionTO;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Set;
import java.util.Iterator;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.farm.IRegion", readonly=false, used=true)
@SuppressWarnings("serial")
public class IRegionListTO<TOType, OntoType> extends ArrayList<IRegionTO<TOType, OntoType>> implements Serializable, Cloneable	
{
    @SuppressWarnings("unused")
    private Long id;


    public Long getId()
    {
        return null; // intentionally, this object can not be persisted!
    }


    public void setId(Long id)
    {
        this.id = id;
    }
    

    @SuppressWarnings("unchecked")
    public IRegionListTO<TOType, OntoType> assignFrom(Set<IRegion> o)
    {
        clear();
        if (o != null) {
            for (IRegion obj : o)
            {
    	//this is the transport object (TO) management of interfaces fields!
		try {
			//obj is an instance of the interface IRegion    
			String TOclassname = obj.getClass().getName().replace("org.seamless_ip.ontologies", "org.seamless_ip.services.transferobjects").concat("TO");
			IRegionTO instance = ((IRegionTO)(Class.forName(TOclassname).newInstance()));
			instance.assignFrom(obj);
			add(instance);
		} catch (Exception e /*ClassNotFoundException, InstantiationException ,IllegalAccessException*/ ){
			e.printStackTrace();
		}
            }
        }
        return this;
    }



    
    public Set<IRegion> assignTo(Set<IRegion> o)
    {
    	// Have to avoid creating persistent instances of NUTSregion with the
    	// same ID, this will cause an exception when the method is called in
    	// a session context (which it usually will be). So instead a slightly
    	// more complex update algorithm is used.
        
        if (o != null) {
        	
        	// remove no longer used items
        	Iterator<IRegion> iter = o.iterator();
        	while (iter.hasNext())
        	{
        		IRegion dbItem = iter.next();
        		boolean found = false;
        		for (IRegionTO<TOType, OntoType> toItem : this)
        		{
        			if (dbItem.getId().equals(toItem.getId()))
        			{
        				found = true;
        				break;
        			}
        		}
        		if (!found)
        			iter.remove();
        	}

            //Update just update Float values, we assume that only Float feld of item(s) 
            //can be updated! 
            for (IRegionTO<TOType, OntoType> toItem : this) {
            	for (IRegion dbItem : o) {
            		if (dbItem.getId() != null && toItem.getId() != null && dbItem.getId().compareTo(toItem.getId()) == 0) {            			
            		}
            	}
            }
            
        	// add new items
            for (IRegionTO<TOType, OntoType> toItem : this)
            {
            	boolean found = false;
            	for (IRegion dbItem : o)
            	{
               		if (toItem.getId() == null)//the id null, 'found' is still false...it will be added
    					break;
               		
            		if (toItem.getId().equals(dbItem.getId()))
            		{
            			found = true;
            			break;
            		}
            	}
            	if (!found)
            	{
                    //TODO: Need to know specific type here!!
                    //o.add(toItem.assignTo(new IRegion()));
	         }   
            }            	
        }
        return o;
    }    


    public boolean equalsTo(Set<IRegion> o)
    {
        if (o == null)
            return false;

        IRegionListTO<TOType, OntoType> to = new IRegionListTO<TOType, OntoType>().assignFrom(o);
        return to.equals(this);
    }


    @Override
    @SuppressWarnings("unchecked")
    public IRegionListTO<TOType, OntoType> clone()
    {
        return (IRegionListTO<TOType, OntoType>) super.clone();
    }
}
	
