/* gromit: GlobalTariffTO .java
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.capri;

import java.io.Serializable;
import java.lang.Float;
import java.lang.Long;
import org.seamless_ip.ontologies.capri.GlobalTariff;
import org.seamless_ip.services.transferobjects.capri.CountryAggregateTO;
import org.seamless_ip.services.transferobjects.capri.ICAPRIParameterTO;
import org.seamless_ip.services.transferobjects.crop.ProductGroupTO;
import org.seamless_ip.services.transferobjects.utils.AbstractTO;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.capri.GlobalTariff", readonly=false, used=true)
@SuppressWarnings("serial")
public class GlobalTariffTO extends AbstractTO implements ICAPRIParameterTO<GlobalTariffTO, GlobalTariff>, Serializable, Cloneable 	
{
	private ProductGroupTO _productgroup;		
	private Long _id;		
	private Float _specifictariff;		
	private Float _baslineSpecifictariff/*transient field*/;		
	private Float _baslineAdvalorem/*transient field*/;		
	private Float _advalorem;		
	private CountryAggregateTO _countryaggregate;		

	/* 
	 * Notes: field commented as 'transient field' are only used to exchange information
	 * between client and server.
	 * 
	 * - They are not persistent (it doesn't exists any field on the database to save that values)
	 * - They are not assigned in the TO object method (assignFrom, assignTO)
	 * - They are not considered in the TO equality methods (hashCode, equals)
	 * 
	 * To use this field you have to do the assignment manually (e.g on the DAO classes that use the 
	 * TO). In the client you will be able to check the content of the filed. 
	 * 
	 */


	public GlobalTariffTO()
	{
		super();
		_productgroup = new ProductGroupTO();
		_countryaggregate = new CountryAggregateTO();
	}

	public static GlobalTariff createDBInstance()
	{
		GlobalTariff dbItem = new GlobalTariff();
		dbItem.setCountryAggregate(CountryAggregateTO.createDBInstance());
		dbItem.setProductGroup(ProductGroupTO.createDBInstance());
		return dbItem;
	}


	public static GlobalTariff createDBInstance(GlobalTariffTO toItem)
	{
		if (toItem != null)
			return toItem.assignTo(createDBInstance());
		else
			return createDBInstance();
	}
	
    public static void releaseDBInstance(GlobalTariff dbItem)
    {
        if (dbItem != null) {
            dbItem.setCountryAggregate(null);
            dbItem.setProductGroup(null);
        }
    }

    public GlobalTariffTO assignFrom(GlobalTariff target)	
	{
		if (target != null)
		{
			try {
					_advalorem = target.getAdValorem();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
				_countryaggregate .assignFrom(target.getCountryAggregate());
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}		
			try {
					_id = target.getId();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
				_productgroup .assignFrom(target.getProductGroup());
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}		
			try {
					_specifictariff = target.getSpecificTariff();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
		}
		return this;
	}
    
    public GlobalTariff assignTo(GlobalTariff target)
    {
        if (target != null) 
        {
			target.setCountryAggregate(_countryaggregate .assignTo(target.getCountryAggregate()));
			target.setProductGroup(_productgroup .assignTo(target.getProductGroup()));
			target.setAdValorem(_advalorem);			
			target.setId(_id);			
			target.setSpecificTariff(_specifictariff);			
        }
        return target;
    }	
    
    public boolean equalsTo(GlobalTariff target)
    {
        if (target == null)
            return false;

        GlobalTariffTO targetTO = new GlobalTariffTO().assignFrom(target);
        return targetTO.equals(this);
    }
    
    @Override
    public GlobalTariffTO clone()
    {
    	GlobalTariffTO clone = new GlobalTariffTO();
		clone.setAdValorem(_advalorem);
		clone.setBaslineAdvalorem(_baslineAdvalorem/*transient field*/);
		clone.setBaslineSpecifictariff(_baslineSpecifictariff/*transient field*/);
		clone.setCountryAggregate(_countryaggregate);
		clone.setId(_id);
		clone.setProductGroup(_productgroup);
		clone.setSpecificTariff(_specifictariff);
        return clone;
    }    
    
    @Override
    public int hashCode()
    {
        int result = 0;
		result = 31 * result + (_productgroup != null ? _productgroup .hashCode() : 0);
		result = 31 * result + (_id != null ? _id .hashCode() : 0);
		result = 31 * result + (_specifictariff != null ? _specifictariff .hashCode() : 0);
		result = 31 * result + (_advalorem != null ? _advalorem .hashCode() : 0);
		result = 31 * result + (_countryaggregate != null ? _countryaggregate .hashCode() : 0);
        return result;
    }    
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof GlobalTariffTO)) return false;

        GlobalTariffTO classTO = (GlobalTariffTO) o;

		if (_productgroup != null ? !_productgroup .equals(classTO._productgroup) : classTO._productgroup != null)
			return false;
		if (_id != null ? !_id .equals(classTO._id) : classTO._id != null)
			return false;
		if (_specifictariff != null ? !_specifictariff .equals(classTO._specifictariff) : classTO._specifictariff != null)
			return false;
		if (_advalorem != null ? !_advalorem .equals(classTO._advalorem) : classTO._advalorem != null)
			return false;
		if (_countryaggregate != null ? !_countryaggregate .equals(classTO._countryaggregate) : classTO._countryaggregate != null)
			return false;
        
        return true;
    }
    
    public Float getAdValorem()
    {
		return _advalorem;
    }
    public Float getBaslineAdvalorem()
    {
		return _baslineAdvalorem/*transient field*/;
    }
    public Float getBaslineSpecifictariff()
    {
		return _baslineSpecifictariff/*transient field*/;
    }
    public CountryAggregateTO getCountryAggregate()
    {
		return _countryaggregate;
    }
    public Long getId()
    {
		return _id;
    }
    public ProductGroupTO getProductGroup()
    {
		return _productgroup;
    }
    public Float getSpecificTariff()
    {
		return _specifictariff;
    }
    public void setAdValorem(Float value)
    {
		_advalorem = value;
    }
    public void setBaslineAdvalorem(Float value)
    {
		_baslineAdvalorem/*transient field*/ = value;
    }
    public void setBaslineSpecifictariff(Float value)
    {
		_baslineSpecifictariff/*transient field*/ = value;
    }
    public void setCountryAggregate(CountryAggregateTO value)
    {
		_countryaggregate = value;
    }
    public void setId(Long value)
    {
		_id = value;
    }
    public void setProductGroup(ProductGroupTO value)
    {
		_productgroup = value;
    }
    public void setSpecificTariff(Float value)
    {
		_specifictariff = value;
    }
}