/* gromit: GrassManagementListTO .java 
 * ==============================================================================
 * (This code was generated by a tool)
 * List of Transport Object class for GrassManagementTO .java
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */

package org.seamless_ip.services.transferobjects.activity;

import org.seamless_ip.ontologies.activity.GrassManagement;
import org.seamless_ip.services.transferobjects.activity.GrassManagementTO;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Set;
import java.util.Iterator;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.activity.GrassManagement", readonly=false, used=true)
@SuppressWarnings("serial")
public class GrassManagementListTO extends ArrayList<GrassManagementTO> implements Serializable, Cloneable	
{
    @SuppressWarnings("unused")
    private Long id;


    public Long getId()
    {
        return null; // intentionally, this object can not be persisted!
    }


    public void setId(Long id)
    {
        this.id = id;
    }
    

    public GrassManagementListTO assignFrom(Set<GrassManagement> o)
    {
        clear();
        if (o != null) {
            for (GrassManagement obj : o)
            {
    			add(new GrassManagementTO().assignFrom(obj));
            }
        }
        return this;
    }



    
    public Set<GrassManagement> assignTo(Set<GrassManagement> o)
    {
    	// Have to avoid creating persistent instances of NUTSregion with the
    	// same ID, this will cause an exception when the method is called in
    	// a session context (which it usually will be). So instead a slightly
    	// more complex update algorithm is used.
        
        if (o != null) {
        	
        	// remove no longer used items
        	Iterator<GrassManagement> iter = o.iterator();
        	while (iter.hasNext())
        	{
        		GrassManagement dbItem = iter.next();
        		boolean found = false;
        		for (GrassManagementTO toItem : this)
        		{
        			if (dbItem.getId().equals(toItem.getId()))
        			{
        				found = true;
        				break;
        			}
        		}
        		if (!found)
        			iter.remove();
        	}

            //Update just update Float values, we assume that only Float feld of item(s) 
            //can be updated! 
            for (GrassManagementTO toItem : this) {
            	for (GrassManagement dbItem : o) {
            		if (dbItem.getId() != null && toItem.getId() != null && dbItem.getId().compareTo(toItem.getId()) == 0) {            			
						if (dbItem.getNitrogenUse().compareTo(toItem.getNitrogenUse()) != 0) {						
							//Update all Floats 
							dbItem.setNitrogenUse(toItem.getNitrogenUse());
            			}
						if (dbItem.getNitrogenUseOrganic().compareTo(toItem.getNitrogenUseOrganic()) != 0) {						
							//Update all Floats 
							dbItem.setNitrogenUseOrganic(toItem.getNitrogenUseOrganic());
            			}
						if (dbItem.getVariableCostsOfHarvestingOfSilage().compareTo(toItem.getVariableCostsOfHarvestingOfSilage()) != 0) {						
							//Update all Floats 
							dbItem.setVariableCostsOfHarvestingOfSilage(toItem.getVariableCostsOfHarvestingOfSilage());
            			}
						if (dbItem.getEndOfGrazingPeriod().compareTo(toItem.getEndOfGrazingPeriod()) != 0) {						
							//Update all Floats 
							dbItem.setEndOfGrazingPeriod(toItem.getEndOfGrazingPeriod());
            			}
						if (dbItem.getVariableCostsOfHarvestingOfHay().compareTo(toItem.getVariableCostsOfHarvestingOfHay()) != 0) {						
							//Update all Floats 
							dbItem.setVariableCostsOfHarvestingOfHay(toItem.getVariableCostsOfHarvestingOfHay());
            			}
						if (dbItem.getVariableCostsOfHarvestingOfPastureForGrazing().compareTo(toItem.getVariableCostsOfHarvestingOfPastureForGrazing()) != 0) {						
							//Update all Floats 
							dbItem.setVariableCostsOfHarvestingOfPastureForGrazing(toItem.getVariableCostsOfHarvestingOfPastureForGrazing());
            			}
						if (dbItem.getBiomassForHay().compareTo(toItem.getBiomassForHay()) != 0) {						
							//Update all Floats 
							dbItem.setBiomassForHay(toItem.getBiomassForHay());
            			}
						if (dbItem.getBiomassForSilage().compareTo(toItem.getBiomassForSilage()) != 0) {						
							//Update all Floats 
							dbItem.setBiomassForSilage(toItem.getBiomassForSilage());
            			}
						if (dbItem.getOverallBiomass().compareTo(toItem.getOverallBiomass()) != 0) {						
							//Update all Floats 
							dbItem.setOverallBiomass(toItem.getOverallBiomass());
            			}
						if (dbItem.getVariableCostsOfHarvestingOfFreshFodder().compareTo(toItem.getVariableCostsOfHarvestingOfFreshFodder()) != 0) {						
							//Update all Floats 
							dbItem.setVariableCostsOfHarvestingOfFreshFodder(toItem.getVariableCostsOfHarvestingOfFreshFodder());
            			}
						if (dbItem.getBiomassForPastureGrazing().compareTo(toItem.getBiomassForPastureGrazing()) != 0) {						
							//Update all Floats 
							dbItem.setBiomassForPastureGrazing(toItem.getBiomassForPastureGrazing());
            			}
						if (dbItem.getBiomassForFreshFodder().compareTo(toItem.getBiomassForFreshFodder()) != 0) {						
							//Update all Floats 
							dbItem.setBiomassForFreshFodder(toItem.getBiomassForFreshFodder());
            			}
						if (dbItem.getVariableCostsConcerningGrasslandWithoutCostsOfHarvest().compareTo(toItem.getVariableCostsConcerningGrasslandWithoutCostsOfHarvest()) != 0) {						
							//Update all Floats 
							dbItem.setVariableCostsConcerningGrasslandWithoutCostsOfHarvest(toItem.getVariableCostsConcerningGrasslandWithoutCostsOfHarvest());
            			}
            		}
            	}
            }
            
        	// add new items
            for (GrassManagementTO toItem : this)
            {
            	boolean found = false;
            	for (GrassManagement dbItem : o)
            	{
               		if (toItem.getId() == null)//the id null, 'found' is still false...it will be added
    					break;
               		
            		if (toItem.getId().equals(dbItem.getId()))
            		{
            			found = true;
            			break;
            		}
            	}
            	if (!found)
            	{
					o.add(toItem.assignTo(new GrassManagement()));
	         }   
            }            	
        }
        return o;
    }    


    public boolean equalsTo(Set<GrassManagement> o)
    {
        if (o == null)
            return false;

        GrassManagementListTO to = new GrassManagementListTO().assignFrom(o);
        return to.equals(this);
    }


    @Override
    public GrassManagementListTO clone()
    {
        return (GrassManagementListTO) super.clone();
    }
}
	
