/* gromit: CropProductTO .java
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.crop;

import java.io.Serializable;
import java.lang.Long;
import java.lang.String;
import java.util.HashSet;
import org.seamless_ip.ontologies.crop.CropProduct;
import org.seamless_ip.ontologies.crop.ProductGroup;
import org.seamless_ip.services.transferobjects.crop.CropTO;
import org.seamless_ip.services.transferobjects.crop.IProductTO;
import org.seamless_ip.services.transferobjects.crop.ProductGroupListTO;
import org.seamless_ip.services.transferobjects.utils.AbstractTO;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.crop.CropProduct", readonly=false, used=true)
@SuppressWarnings("serial")
public class CropProductTO extends AbstractTO implements IProductTO<CropProductTO, CropProduct>, Serializable, Cloneable 	
{
	private String _label_gms;		
	private String _label_en;		
	private ProductGroupListTO _ispartofproductgroups;		
	private Long _id;		
	private CropTO _ofcrop;		



	public CropProductTO()
	{
		super();
		_ispartofproductgroups = new ProductGroupListTO();
		_ofcrop = new CropTO();
	}

	public static CropProduct createDBInstance()
	{
		CropProduct dbItem = new CropProduct();
		dbItem.setIsPartOfProductGroups(new HashSet<ProductGroup>());
		dbItem.setOfCrop(CropTO.createDBInstance());
		return dbItem;
	}


	public static CropProduct createDBInstance(CropProductTO toItem)
	{
		if (toItem != null)
			return toItem.assignTo(createDBInstance());
		else
			return createDBInstance();
	}
	
    public static void releaseDBInstance(CropProduct dbItem)
    {
        if (dbItem != null) {
            dbItem.setIsPartOfProductGroups(null);
            dbItem.setOfCrop(null);
        }
    }

    public CropProductTO assignFrom(CropProduct target)	
	{
		if (target != null)
		{
			try {
					_id = target.getId();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
				_ispartofproductgroups .assignFrom(target.getIsPartOfProductGroups());
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}		
			try {
					_label_en = target.getLabel_en();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_label_gms = target.getLabel_gms();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
				_ofcrop .assignFrom(target.getOfCrop());
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}		
		}
		return this;
	}
    
    public CropProduct assignTo(CropProduct target)
    {
        if (target != null) 
        {
			target.setIsPartOfProductGroups(_ispartofproductgroups .assignTo(target.getIsPartOfProductGroups()));
			target.setOfCrop(_ofcrop .assignTo(target.getOfCrop()));
			target.setId(_id);			
			target.setLabel_en(_label_en);			
			target.setLabel_gms(_label_gms);			
        }
        return target;
    }	
    
    public boolean equalsTo(CropProduct target)
    {
        if (target == null)
            return false;

        CropProductTO targetTO = new CropProductTO().assignFrom(target);
        return targetTO.equals(this);
    }
    
    @Override
    public CropProductTO clone()
    {
    	CropProductTO clone = new CropProductTO();
		clone.setId(_id);
		clone.setIsPartOfProductGroups(_ispartofproductgroups);
		clone.setLabel_en(_label_en);
		clone.setLabel_gms(_label_gms);
		clone.setOfCrop(_ofcrop);
        return clone;
    }    
    
    @Override
    public int hashCode()
    {
        int result = 0;
		result = 31 * result + (_label_gms != null ? _label_gms .hashCode() : 0);
		result = 31 * result + (_label_en != null ? _label_en .hashCode() : 0);
		result = 31 * result + (_ispartofproductgroups != null ? _ispartofproductgroups .hashCode() : 0);
		result = 31 * result + (_id != null ? _id .hashCode() : 0);
		result = 31 * result + (_ofcrop != null ? _ofcrop .hashCode() : 0);
        return result;
    }    
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof CropProductTO)) return false;

        CropProductTO classTO = (CropProductTO) o;

		if (_label_gms != null ? !_label_gms .equals(classTO._label_gms) : classTO._label_gms != null)
			return false;
		if (_label_en != null ? !_label_en .equals(classTO._label_en) : classTO._label_en != null)
			return false;
		if (_ispartofproductgroups != null ? !_ispartofproductgroups .equals(classTO._ispartofproductgroups) : classTO._ispartofproductgroups != null)
			return false;
		if (_id != null ? !_id .equals(classTO._id) : classTO._id != null)
			return false;
		if (_ofcrop != null ? !_ofcrop .equals(classTO._ofcrop) : classTO._ofcrop != null)
			return false;
        
        return true;
    }
    
    public Long getId()
    {
		return _id;
    }
    public ProductGroupListTO getIsPartOfProductGroups()
    {
		return _ispartofproductgroups;
    }
    public String getLabel_en()
    {
		return _label_en;
    }
    public String getLabel_gms()
    {
		return _label_gms;
    }
    public CropTO getOfCrop()
    {
		return _ofcrop;
    }
    public void setId(Long value)
    {
		_id = value;
    }
    public void setIsPartOfProductGroups(ProductGroupListTO value)
    {
		_ispartofproductgroups = value;
    }
    public void setLabel_en(String value)
    {
		_label_en = value;
    }
    public void setLabel_gms(String value)
    {
		_label_gms = value;
    }
    public void setOfCrop(CropTO value)
    {
		_ofcrop = value;
    }
}