/* gromit: FarmConstraintTO .java
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.farmopt;

import java.io.Serializable;
import java.lang.Boolean;
import java.lang.Long;
import org.seamless_ip.ontologies.farmopt.FarmConstraint;
import org.seamless_ip.services.transferobjects.farm.RepresentativeFarmTO;
import org.seamless_ip.services.transferobjects.utils.AbstractTO;
import org.seamless_ip.services.transferobjects.utils.TO;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.farmopt.FarmConstraint", readonly=false, used=true)
@SuppressWarnings("serial")
public class FarmConstraintTO extends AbstractTO implements TO<FarmConstraintTO, FarmConstraint>, Serializable, Cloneable 	
{
	private RepresentativeFarmTO _representativefarm;		
	private Long _id;		
	private Boolean _enabled;		



	public FarmConstraintTO()
	{
		super();
		_representativefarm = new RepresentativeFarmTO();
	}

	public static FarmConstraint createDBInstance()
	{
		FarmConstraint dbItem = new FarmConstraint();
		dbItem.setEnabled(new Boolean(false));
		dbItem.setRepresentativeFarm(RepresentativeFarmTO.createDBInstance());
		return dbItem;
	}


	public static FarmConstraint createDBInstance(FarmConstraintTO toItem)
	{
		if (toItem != null)
			return toItem.assignTo(createDBInstance());
		else
			return createDBInstance();
	}
	
    public static void releaseDBInstance(FarmConstraint dbItem)
    {
        if (dbItem != null) {
            dbItem.setRepresentativeFarm(null);
        }
    }

    public FarmConstraintTO assignFrom(FarmConstraint target)	
	{
		if (target != null)
		{
			try {
					_enabled = target.getEnabled();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_id = target.getId();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
				_representativefarm .assignFrom(target.getRepresentativeFarm());
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}		
		}
		return this;
	}
    
    public FarmConstraint assignTo(FarmConstraint target)
    {
        if (target != null) 
        {
			target.setRepresentativeFarm(_representativefarm .assignTo(target.getRepresentativeFarm()));
			target.setEnabled(_enabled);			
			target.setId(_id);			
        }
        return target;
    }	
    
    public boolean equalsTo(FarmConstraint target)
    {
        if (target == null)
            return false;

        FarmConstraintTO targetTO = new FarmConstraintTO().assignFrom(target);
        return targetTO.equals(this);
    }
    
    @Override
    public FarmConstraintTO clone()
    {
    	FarmConstraintTO clone = new FarmConstraintTO();
		clone.setEnabled(_enabled);
		clone.setId(_id);
		clone.setRepresentativeFarm(_representativefarm);
        return clone;
    }    
    
    @Override
    public int hashCode()
    {
        int result = 0;
		result = 31 * result + (_representativefarm != null ? _representativefarm .hashCode() : 0);
		result = 31 * result + (_id != null ? _id .hashCode() : 0);
		result = 31 * result + (_enabled != null ? _enabled .hashCode() : 0);
        return result;
    }    
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof FarmConstraintTO)) return false;

        FarmConstraintTO classTO = (FarmConstraintTO) o;

		if (_representativefarm != null ? !_representativefarm .equals(classTO._representativefarm) : classTO._representativefarm != null)
			return false;
		if (_id != null ? !_id .equals(classTO._id) : classTO._id != null)
			return false;
		if (_enabled != null ? !_enabled .equals(classTO._enabled) : classTO._enabled != null)
			return false;
        
        return true;
    }
    
    public Boolean getEnabled()
    {
		return _enabled;
    }
    public Long getId()
    {
		return _id;
    }
    public RepresentativeFarmTO getRepresentativeFarm()
    {
		return _representativefarm;
    }
    public void setEnabled(Boolean value)
    {
		_enabled = value;
    }
    public void setId(Long value)
    {
		_id = value;
    }
    public void setRepresentativeFarm(RepresentativeFarmTO value)
    {
		_representativefarm = value;
    }
}