/* gromit: ModelTO .java
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.seamproj;

import java.io.Serializable;
import java.lang.Long;
import java.lang.String;
import java.util.HashSet;
import org.seamless_ip.ontologies.seamproj.Model;
import org.seamless_ip.ontologies.seamproj.SpatialScale;
import org.seamless_ip.services.transferobjects.seamproj.SpatialScaleListTO;
import org.seamless_ip.services.transferobjects.utils.AbstractTO;
import org.seamless_ip.services.transferobjects.utils.EnumTO;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.seamproj.Model", readonly=false, used=true)
@SuppressWarnings("serial")
public class ModelTO extends AbstractTO implements EnumTO<ModelTO, Model>, Serializable, Cloneable 	
{
	private String _version;		
	private String _name;		
	private String _description;		
	private SpatialScaleListTO _spatialscales;		
	private Long _id;		



	public ModelTO()
	{
		super();
		_spatialscales = new SpatialScaleListTO();
	}

	public static Model createDBInstance()
	{
		Model dbItem = new Model();
		dbItem.setSpatialScales(new HashSet<SpatialScale>());
		return dbItem;
	}


	public static Model createDBInstance(ModelTO toItem)
	{
		if (toItem != null)
			return toItem.assignTo(createDBInstance());
		else
			return createDBInstance();
	}
	
    public static void releaseDBInstance(Model dbItem)
    {
        if (dbItem != null) {
            dbItem.setSpatialScales(null);
        }
    }

    public ModelTO assignFrom(Model target)	
	{
		if (target != null)
		{
			try {
					_description = target.getDescription();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_id = target.getId();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_name = target.getName();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
				_spatialscales .assignFrom(target.getSpatialScales());
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}		
			try {
					_version = target.getVersion();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
		}
		return this;
	}
    
    public Model assignTo(Model target)
    {
        if (target != null) 
        {
			target.setSpatialScales(_spatialscales .assignTo(target.getSpatialScales()));
			target.setDescription(_description);			
			target.setId(_id);			
			target.setName(_name);			
			target.setVersion(_version);			
        }
        return target;
    }	
    
    public boolean equalsTo(Model target)
    {
        if (target == null)
            return false;

        ModelTO targetTO = new ModelTO().assignFrom(target);
        return targetTO.equals(this);
    }
    
    @Override
    public ModelTO clone()
    {
    	ModelTO clone = new ModelTO();
		clone.setDescription(_description);
		clone.setId(_id);
		clone.setName(_name);
		clone.setSpatialScales(_spatialscales);
		clone.setVersion(_version);
        return clone;
    }    
    
    @Override
    public int hashCode()
    {
        int result = 0;
		result = 31 * result + (_version != null ? _version .hashCode() : 0);
		result = 31 * result + (_name != null ? _name .hashCode() : 0);
		result = 31 * result + (_description != null ? _description .hashCode() : 0);
		result = 31 * result + (_spatialscales != null ? _spatialscales .hashCode() : 0);
		result = 31 * result + (_id != null ? _id .hashCode() : 0);
        return result;
    }    
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof ModelTO)) return false;

        ModelTO classTO = (ModelTO) o;

		if (_version != null ? !_version .equals(classTO._version) : classTO._version != null)
			return false;
		if (_name != null ? !_name .equals(classTO._name) : classTO._name != null)
			return false;
		if (_description != null ? !_description .equals(classTO._description) : classTO._description != null)
			return false;
		if (_spatialscales != null ? !_spatialscales .equals(classTO._spatialscales) : classTO._spatialscales != null)
			return false;
		if (_id != null ? !_id .equals(classTO._id) : classTO._id != null)
			return false;
        
        return true;
    }
    
    public String getDescription()
    {
		return _description;
    }
    public Long getId()
    {
		return _id;
    }
    public String getLabel()
    {
		return _name;
    }
    public String getName()
    {
		return _name;
    }
    public SpatialScaleListTO getSpatialScales()
    {
		return _spatialscales;
    }
    public String getVersion()
    {
		return _version;
    }
    public void setDescription(String value)
    {
		_description = value;
    }
    public void setId(Long value)
    {
		_id = value;
    }
    public void setName(String value)
    {
		_name = value;
    }
    public void setSpatialScales(SpatialScaleListTO value)
    {
		_spatialscales = value;
    }
    public void setVersion(String value)
    {
		_version = value;
    }
}