/* gromit: NarrativeOptionTO .java
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.seamproj;

import java.io.Serializable;
import java.lang.Long;
import java.lang.String;
import org.seamless_ip.ontologies.seamproj.NarrativeOption;
import org.seamless_ip.services.transferobjects.utils.AbstractTO;
import org.seamless_ip.services.transferobjects.utils.TO;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.seamproj.NarrativeOption", readonly=false, used=true)
@SuppressWarnings("serial")
public class NarrativeOptionTO extends AbstractTO implements TO<NarrativeOptionTO, NarrativeOption>, Serializable, Cloneable 	
{
	private String _value;		
	private String _option;		
	private Long _id;		



	public NarrativeOptionTO()
	{
		super();
	}

	public static NarrativeOption createDBInstance()
	{
		NarrativeOption dbItem = new NarrativeOption();
		return dbItem;
	}


	public static NarrativeOption createDBInstance(NarrativeOptionTO toItem)
	{
		if (toItem != null)
			return toItem.assignTo(createDBInstance());
		else
			return createDBInstance();
	}
	
    public static void releaseDBInstance(NarrativeOption dbItem)
    {
        if (dbItem != null) {
        }
    }

    public NarrativeOptionTO assignFrom(NarrativeOption target)	
	{
		if (target != null)
		{
			try {
					_id = target.getId();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_option = target.getOption();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_value = target.getValue();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
		}
		return this;
	}
    
    public NarrativeOption assignTo(NarrativeOption target)
    {
        if (target != null) 
        {
			target.setId(_id);			
			target.setOption(_option);			
			target.setValue(_value);			
        }
        return target;
    }	
    
    public boolean equalsTo(NarrativeOption target)
    {
        if (target == null)
            return false;

        NarrativeOptionTO targetTO = new NarrativeOptionTO().assignFrom(target);
        return targetTO.equals(this);
    }
    
    @Override
    public NarrativeOptionTO clone()
    {
    	NarrativeOptionTO clone = new NarrativeOptionTO();
		clone.setId(_id);
		clone.setOption(_option);
		clone.setValue(_value);
        return clone;
    }    
    
    @Override
    public int hashCode()
    {
        int result = 0;
		result = 31 * result + (_value != null ? _value .hashCode() : 0);
		result = 31 * result + (_option != null ? _option .hashCode() : 0);
		result = 31 * result + (_id != null ? _id .hashCode() : 0);
        return result;
    }    
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof NarrativeOptionTO)) return false;

        NarrativeOptionTO classTO = (NarrativeOptionTO) o;

		if (_value != null ? !_value .equals(classTO._value) : classTO._value != null)
			return false;
		if (_option != null ? !_option .equals(classTO._option) : classTO._option != null)
			return false;
		if (_id != null ? !_id .equals(classTO._id) : classTO._id != null)
			return false;
        
        return true;
    }
    
    public Long getId()
    {
		return _id;
    }
    public String getOption()
    {
		return _option;
    }
    public String getValue()
    {
		return _value;
    }
    public void setId(Long value)
    {
		_id = value;
    }
    public void setOption(String value)
    {
		_option = value;
    }
    public void setValue(String value)
    {
		_value = value;
    }
}