/* gromit: NaturalResourceFocusTO .java
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 * - Ioannis Athanasiadis; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Benny Johnsson; Lund University
 * - Rob Knapen; Alterra, Wageningen UR
 * - Hongtao Li; IDSIA Dalle Molle Institute for Artificial Intelligence
 * - Michiel Rop; Alterra, Wageningen UR / ilionX
 * - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.pica;

import java.io.Serializable;
import java.lang.Long;
import java.lang.String;
import org.seamless_ip.ontologies.pica.NaturalResourceFocus;
import org.seamless_ip.services.transferobjects.utils.AbstractTO;
import org.seamless_ip.services.transferobjects.utils.TO;
import org.seamless_ip.services.transferobjects.utils.CodegeneratorSettings;

@CodegeneratorSettings(sourcename="org.seamless_ip.ontologies.pica.NaturalResourceFocus", readonly=false, used=true)
@SuppressWarnings("serial")
public class NaturalResourceFocusTO extends AbstractTO implements TO<NaturalResourceFocusTO, NaturalResourceFocus>, Serializable, Cloneable 	
{
	private String _name;		
	private String _description;		
	private Long _id;		



	public NaturalResourceFocusTO()
	{
		super();
	}

	public static NaturalResourceFocus createDBInstance()
	{
		NaturalResourceFocus dbItem = new NaturalResourceFocus();
		return dbItem;
	}


	public static NaturalResourceFocus createDBInstance(NaturalResourceFocusTO toItem)
	{
		if (toItem != null)
			return toItem.assignTo(createDBInstance());
		else
			return createDBInstance();
	}
	
    public static void releaseDBInstance(NaturalResourceFocus dbItem)
    {
        if (dbItem != null) {
        }
    }

    public NaturalResourceFocusTO assignFrom(NaturalResourceFocus target)	
	{
		if (target != null)
		{
			try {
					_description = target.getDescription();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_id = target.getId();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
			try {
					_name = target.getName();
			} catch(Exception e)
			{
				//to catch hibernate exception throwed when null value is getted
			}			
		}
		return this;
	}
    
    public NaturalResourceFocus assignTo(NaturalResourceFocus target)
    {
        if (target != null) 
        {
			target.setDescription(_description);			
			target.setId(_id);			
			target.setName(_name);			
        }
        return target;
    }	
    
    public boolean equalsTo(NaturalResourceFocus target)
    {
        if (target == null)
            return false;

        NaturalResourceFocusTO targetTO = new NaturalResourceFocusTO().assignFrom(target);
        return targetTO.equals(this);
    }
    
    @Override
    public NaturalResourceFocusTO clone()
    {
    	NaturalResourceFocusTO clone = new NaturalResourceFocusTO();
		clone.setDescription(_description);
		clone.setId(_id);
		clone.setName(_name);
        return clone;
    }    
    
    @Override
    public int hashCode()
    {
        int result = 0;
		result = 31 * result + (_name != null ? _name .hashCode() : 0);
		result = 31 * result + (_description != null ? _description .hashCode() : 0);
		result = 31 * result + (_id != null ? _id .hashCode() : 0);
        return result;
    }    
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (!(o instanceof NaturalResourceFocusTO)) return false;

        NaturalResourceFocusTO classTO = (NaturalResourceFocusTO) o;

		if (_name != null ? !_name .equals(classTO._name) : classTO._name != null)
			return false;
		if (_description != null ? !_description .equals(classTO._description) : classTO._description != null)
			return false;
		if (_id != null ? !_id .equals(classTO._id) : classTO._id != null)
			return false;
        
        return true;
    }
    
    public String getDescription()
    {
		return _description;
    }
    public Long getId()
    {
		return _id;
    }
    public String getName()
    {
		return _name;
    }
    public void setDescription(String value)
    {
		_description = value;
    }
    public void setId(Long value)
    {
		_id = value;
    }
    public void setName(String value)
    {
		_name = value;
    }
}